// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package golang_graphql_authentication

type LoginUserInput struct {
	Email       string `json:"email"`
	PhoneNumber string `json:"phoneNumber"`
	Password    string `json:"password"`
}

type LoginUserPayload struct {
	User       *User   `json:"user"`
	JwtToken   *string `json:"jwtToken"`
	StatusCode string  `json:"statusCode"`
	Message    string  `json:"message"`
}

type RegisterUserInput struct {
	FirstName   string `json:"firstName"`
	LastName    string `json:"lastName"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phoneNumber"`
	Password    string `json:"password"`
}

type RegisterUserPayload struct {
	User       *User   `json:"user"`
	JwtToken   *string `json:"jwtToken"`
	StatusCode string  `json:"statusCode"`
	Message    string  `json:"message"`
}

type User struct {
	ID          string `json:"id"`
	FirstName   string `json:"firstName"`
	LastName    string `json:"lastName"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phoneNumber"`
}

type UserPayload struct {
	User       *User  `json:"user"`
	StatusCode string `json:"statusCode"`
	Message    string `json:"message"`
}
