// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package golang_graphql_authentication

type FieldErrors struct {
	Field string `json:"field"`
	Error string `json:"error"`
}

type LoginUserInput struct {
	Email       string `json:"email"`
	PhoneNumber string `json:"phoneNumber"`
	Password    string `json:"password"`
}

type LoginUserPayload struct {
	User       *User   `json:"user"`
	JwtToken   *string `json:"jwtToken"`
	StatusCode int     `json:"statusCode"`
	Message    string  `json:"message"`
}

type RegisterUserInput struct {
	FirstName   string `json:"firstName"`
	LastName    string `json:"lastName"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phoneNumber"`
	Password    string `json:"password"`
}

type RegisterUserPayload struct {
	User        *User          `json:"user"`
	JwtToken    *string        `json:"jwtToken"`
	StatusCode  int            `json:"statusCode"`
	Message     string         `json:"message"`
	FieldErrors []*FieldErrors `json:"fieldErrors"`
}

type User struct {
	ID          string `json:"id"`
	FirstName   string `json:"firstName"`
	LastName    string `json:"lastName"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phoneNumber"`
}

type UserPayload struct {
	User       *User  `json:"user"`
	StatusCode int    `json:"statusCode"`
	Message    string `json:"message"`
}
